spring:
  datasource:
    username: root
    password: root
    url: jdbc:h2:~/quotes
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
